# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenapp', '0003_auto_20170501_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabriek',
            name='telefoonnummer',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')]),
        ),
    ]
